### ISSUE TITLE
add a new bypass method

### ISSUE THREAD

**Issue by mhmh55516** [hanhanhanz/forothree#2]
Hi, can you add this bypass way 
![image](https://user-images.githubusercontent.com/28407784/117747358-54fbb380-b20e-11eb-8d42-70e123e80af7.png)

https://twitter.com/_Bugbountytips_/status/1366696960313470977

**Comment by hanhanhanz** [comment]
![DeepinScreenshot_select-area_20210514161308](https://user-images.githubusercontent.com/69136662/118249169-50195700-b4cf-11eb-920c-6511284d67fa.png)

i add the bypass method so every 403 url feed to the forothree will check for X-Rewrite-URL, not just for xmlrpc
